### ISSUE TITLE
cki is getting non kcidb compliant data

### ISSUE THREAD

**Issue by wizardofoz123** [virt-s1/cki#1]
Hi, 

test result code that CKI gets through umb aren't kcidb compliant and it's causing issues.
For test results we use "ERROR", "FAIL", "PASS", "DONE", "SKIP".

At the very least I need to know what 'ABORT' or other result codes mean.

https://github.com/virt-s1/cki/blob/e998306e208923bdc2893899e57d1997d46ff13c/cki-send.py#L58

**Comment by inakimalerba** [comment]
@mkenigs this should be resolved now :)
